# Generated by Django 2.2.3 on 2019-10-06 20:24

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_reactuser'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='reactuser',
            managers=[
                ('objects', api.models.ReactManager()),
            ],
        ),
        migrations.AddField(
            model_name='reactuser',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
