# Generated by Django 2.2.3 on 2019-10-06 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191006_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='reactuser',
            name='admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reactuser',
            name='staff',
            field=models.BooleanField(default=False),
        ),
    ]
