# Generated by Django 2.2.3 on 2019-10-08 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20191006_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='reactuser',
            name='token',
            field=models.CharField(default='', max_length=255),
        ),
    ]
